---
- hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      apt:
        upgrade: yes
        autoremove: yes
        autoclean: yes

- hosts: HAproxy
  become: yes
  become_method: sudo
  tasks:
    - name: HAproxy Update
      apt:
        update_cache: yes

    - name: Install HAproxy
      apt:
        name: haproxy
        state: latest

- hosts: webservers
  become: yes
  become_method: sudo
  tasks:
    - name: Webservers update
      apt:
        update_cache: yes

    - name: install python3-pip
      apt:
        name: python3-pip
        state: latest
        update_cache: yes

    - name: flask installation
      pip:
        name: flask
        state: latest

    - name: install Gunicorn
      apt:
        name: gunicorn

    - name: copy the flask app code to the servers
      copy:
        src: /$PWD/application2.py
        dest: /home/ubuntu/application2.py
        owner: ubuntu
        mode: '0644'

    - name: Running Flask application
      shell: gunicorn -w 2 -D -b 0.0.0.0:5000 application2:app

- name: Retrieve and Configure HAProxy with Web Server IPs
  hosts: HAproxy
  become: yes
  tasks:
    - name: Retrieve IP addresses of web servers
      add_host:
        name: "{{ item }}"
        groups: web_server_ips
      with_items: "{{ groups['webservers'] }}"

    - name: Template HAProxy configuration with retrieved IPs
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      notify: Restart HAProxy

  handlers:
    - name: Restart HAProxy
      service:
        name: haproxy
        state: restarted

- name: Deploy Application and Configure HAProxy
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Gather Facts
      setup:

    - name: Update package cache
      apt:
        update_cache: yes
      become: yes

    - name: Upgrade packages
      apt:
        upgrade: dist
        update_cache: yes
      become: yes
